version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/development/mongodb/data:/data/db

  nodejs:
    image: acikabubo/nodejs:mongodb
    container_name: nodejs
    ports:
      - 3000:3000
    volumes:
      - ~/development/workspace/nodejs:/home/$USER/workspace
